### ISSUE TITLE
Remote connection closed by OpenAI

### ISSUE THREAD

**Issue by GrandMoff100** [oneil512/INSIGHT#36]
Sometimes OpenAI closed the remote connection on us. Should be handled gracefully with a retry decorator.
```
Traceback (most recent call last):
  File "/home/nate/INSIGHT/main.py", line 225, in <module>
    run(api_key=api_key, OBJECTIVE=objective, MAX_ITERATIONS=iterations, TOOLS=tools, my_data_path=my_data_path, reload_path=reload_path)
  File "/home/nate/INSIGHT/main.py", line 177, in run
    result, task, task_list, summaries = run_(
  File "/home/nate/INSIGHT/main.py", line 76, in run_
    result, result_is_python = worker_agent(OBJECTIVE, task, master_index, cache, TOOLS)
  File "/home/nate/INSIGHT/agents.py", line 149, in worker_agent
    response = get_gpt_completion(prompt, engine="text-davinci-003", temp=0.0)
  File "/home/nate/INSIGHT/.venv/lib/python3.10/site-packages/backoff/_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
  File "/home/nate/INSIGHT/utils.py", line 648, in get_gpt_completion
    response = openai.Completion.create(
  File "/home/nate/INSIGHT/.venv/lib/python3.10/site-packages/openai/api_resources/completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/home/nate/INSIGHT/.venv/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/home/nate/INSIGHT/.venv/lib/python3.10/site-packages/openai/api_requestor.py", line 216, in request
    result = self.request_raw(
  File "/home/nate/INSIGHT/.venv/lib/python3.10/site-packages/openai/api_requestor.py", line 529, in request_raw
    raise error.APIConnectionError(
openai.error.APIConnectionError: Error communicating with OpenAI: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

**Comment by oneil512** [comment]
Done! see [commit](https://github.com/oneil512/INSIGHT/commit/40385a53c3594ba11f4481adb2c62fec795896a3)
