### ISSUE TITLE
PUBMED tool error - `TypeError: 'NoneType' object is not iterable`

### ISSUE THREAD

**Issue by batmanscode** [oneil512/INSIGHT#39]
```bash
query_term = 'toe numbness', retmax = 10, retstart = 0
Exception executing code from api.pubmed_wrapper import pubmed_wrapper
query_term = 'toe numbness', retmax = 10, retstart = 0
ret = pubmed_wrapper(query_term, retmax, retstart), invalid syntax. Maybe you meant '==' or ':=' instead of '='? (<string>, line 2)
Cannot parse pubmed result, expected xml. a bytes-like object is required, not 'NoneType'
Adding whole document. Note this will lead to suboptimal results.
Task 'PUBMED: Research common causes of toe numbness' failed. Code NOTE: Code did not run succesfully

from api.pubmed_wrapper import pubmed_wrapper
query_term = 'toe numbness', retmax = 10, retstart = 0
ret = pubmed_wrapper(query_term, retmax, retstart) did not run succesfully.
Traceback (most recent call last):
  File "/workspaces/INSIGHT/main.py", line 225, in <module>
    run(api_key=api_key, OBJECTIVE=objective, MAX_ITERATIONS=iterations, TOOLS=tools, my_data_path=my_data_path, reload_path=reload_path)
  File "/workspaces/INSIGHT/main.py", line 177, in run
    result, task, task_list, summaries = run_(
                                         ^^^^^
  File "/workspaces/INSIGHT/main.py", line 89, in run_
    handle_results(result, index, doc_store, doc_store_task_key, task_id_counter, RESULT_CUTOFF)
  File "/workspaces/INSIGHT/utils.py", line 530, in handle_results
    for i, r in enumerate(result):
                ^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
```

**Comment by batmanscode** [comment]
@oneil512 gentle pump

**Comment by oneil512** [comment]
This is fixed here https://github.com/oneil512/INSIGHT/pull/41
